/**
 * Write or check the Rainbow/Mini ownership manifest.
 *
 *   npm run db:manifest             read the LOCAL e2e database and rewrite
 *                                   supabase/rainbow-owned-objects.json and
 *                                   supabase/RAINBOW-OWNED-OBJECTS.md
 *   npm run db:manifest -- --check  read it and FAIL if it differs from the
 *                                   committed manifest (the CI gate)
 *   npm run db:manifest -- --out <dir> [--label <text>]
 *                                   write the inventory of whatever the
 *                                   configured local database currently
 *                                   holds to <dir> instead (used to snapshot a
 *                                   "before" state for a change preview)
 *
 * Reads only. It connects to the e2e stack's database and nothing else: the
 * same safety guard every e2e command runs refuses anything that is not the
 * disposable local stack, so this can never inventory — let alone touch —
 * the hosted project.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import pg from "pg";
import { REPO_ROOT, assertIsE2eStack, guardContext, loadE2eConfig } from "../env.ts";
import { assertDisposableTarget, UnsafeTargetError } from "../safety.ts";
import { collectInventory, diffInventories, renderInventoryMarkdown, type Inventory } from "./lib/inventory.ts";

export const MANIFEST_JSON = path.join(REPO_ROOT, "supabase", "rainbow-owned-objects.json");
export const MANIFEST_MD = path.join(REPO_ROOT, "supabase", "RAINBOW-OWNED-OBJECTS.md");

const PREAMBLE = `
GENERATED by \`npm run db:manifest\` from a database built from \`supabase/migrations/\`
alone. Do not edit by hand: change the baseline, rebuild, regenerate.

This is the complete list of database objects Rainbow Categories and Mini Categories
own. It is the contract behind two rules:

1. **Rainbow references nothing outside this list** (plus GoTrue's own \`auth.uid()\`,
   \`auth.users\` and \`auth.identities\`). While Rainbow shares a Supabase project with
   other games, their objects (\`xw_*\`, \`cv_*\`, \`wtf_*\`, …) are not Rainbow's and never
   appear here.
2. **The scoped teardown drops exactly this list and nothing else** — see
   \`e2e/scripts/teardown-sql.ts\`.

\`npm run db:manifest -- --check\` fails when the baseline no longer produces this
manifest, so an object created by hand, or a migration that forgot a grant or a policy,
shows up as a diff instead of as a surprise on a blank project.
`;

function parseArgs(argv: string[]) {
  const args = { check: false, out: null as string | null, label: null as string | null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--check") args.check = true;
    else if (argv[i] === "--out") args.out = argv[++i] ?? null;
    else if (argv[i] === "--label") args.label = argv[++i] ?? null;
  }
  return args;
}

export function readCommittedManifest(): Inventory | null {
  if (!existsSync(MANIFEST_JSON)) return null;
  return JSON.parse(readFileSync(MANIFEST_JSON, "utf8")) as Inventory;
}

async function main(): Promise<number> {
  const args = parseArgs(process.argv.slice(2));
  const config = loadE2eConfig();
  try {
    assertDisposableTarget("db:manifest", config, guardContext());
    assertIsE2eStack(config.apiUrl, config.dbUrl);
  } catch (error) {
    if (error instanceof UnsafeTargetError || error instanceof Error) {
      console.error(`\n${error.message}\n`);
      return 2;
    }
    throw error;
  }

  const client = new pg.Client({ connectionString: config.dbUrl });
  await client.connect();
  let inventory: Inventory;
  try {
    inventory = await collectInventory(client);
  } finally {
    await client.end();
  }

  const json = JSON.stringify(inventory, null, 2) + "\n";

  if (args.out) {
    mkdirSync(args.out, { recursive: true });
    const label = args.label ?? "Database inventory";
    writeFileSync(path.join(args.out, "inventory.json"), json, "utf8");
    writeFileSync(
      path.join(args.out, "inventory.md"),
      renderInventoryMarkdown(inventory, label, `Snapshot of ${config.dbUrl.replace(/:[^:@/]*@/, ":****@")} taken ${new Date().toISOString()}.`),
      "utf8"
    );
    console.log(`Wrote ${path.join(args.out, "inventory.json")} and inventory.md`);
    return 0;
  }

  if (args.check) {
    const committed = readCommittedManifest();
    if (!committed) {
      console.error(`\nNo committed manifest at ${MANIFEST_JSON}. Run \`npm run db:manifest\` first.\n`);
      return 3;
    }
    const diff = diffInventories(committed, inventory);
    if (diff.length) {
      console.error("\nThe database does NOT match the committed ownership manifest:\n");
      for (const line of diff) console.error(`  - ${line}`);
      console.error(
        "\nIf the baseline changed on purpose, rebuild the local database (`npm run e2e:reset`) and run\n" +
          "`npm run db:manifest` to regenerate; then review and commit the manifest with the change.\n"
      );
      return 1;
    }
    console.log(
      `Manifest OK: ${inventory.tables.length} tables, ${inventory.functions.length} functions, ` +
        `${inventory.tables.reduce((n, t) => n + t.policies.length, 0)} policies match ${path.relative(REPO_ROOT, MANIFEST_JSON)}.`
    );
    return 0;
  }

  writeFileSync(MANIFEST_JSON, json, "utf8");
  writeFileSync(
    MANIFEST_MD,
    renderInventoryMarkdown(inventory, "Rainbow / Mini owned database objects", PREAMBLE),
    "utf8"
  );
  console.log(`Wrote ${path.relative(REPO_ROOT, MANIFEST_JSON)} and ${path.relative(REPO_ROOT, MANIFEST_MD)}`);
  return 0;
}

main().then(
  (code) => process.exit(code),
  (error) => {
    console.error(`\n${error instanceof Error ? error.stack ?? error.message : String(error)}\n`);
    process.exit(1);
  }
);
