-- REHEARSAL: Rainbow/Mini beta-era teardown for the SHARED beta project.
-- GENERATED by `npm run db:teardown-sql` from the ownership manifest and the beta-era inventory.
-- Do not edit by hand. Every statement names one object; there is no cascade and no wildcard.
-- Tables: 24. Functions: 62. Types: 1. Storage policies: 0.
-- Auth users kept: 1.

begin;
set local lock_timeout = '10s';
set local statement_timeout = '10min';

-- 0. Refuse to run if the keep-list does not match reality.
do $$
declare _missing integer; _to_delete integer;
begin
  select count(*) into _missing from unnest(array['00000000-0000-0000-0000-000000000000']::uuid[]) k(id)
   where not exists (select 1 from auth.users u where u.id = k.id);
  if _missing > 0 then raise exception 'Aborting: % keep-list auth user(s) do not exist in this project', _missing; end if;
  select count(*) into _to_delete from auth.users u where u.id <> all(array['00000000-0000-0000-0000-000000000000']::uuid[]);
  raise notice 'auth users that will be deleted: %', _to_delete;
end $$;

-- 1. Storage policies: none listed yet (the Phase 2 comparison fills extra-objects.json).

-- 2. Row-level-security policies and triggers on Rainbow tables (they reference Rainbow functions).
drop policy if exists "Admins can manage archive access" on public."archive_access";
drop policy if exists "Admins can manage puzzle groups" on public."puzzle_groups";
drop policy if exists "Admins can manage puzzles" on public."puzzles";
drop policy if exists "Admins can manage roles" on public."user_roles";
drop policy if exists "Admins can read all game sessions" on public."game_sessions";
drop policy if exists "Admins can read all guess events" on public."guess_events";
drop policy if exists "Admins can read all hint events" on public."hint_events";
drop policy if exists "Admins can read all puzzle versions" on public."puzzle_versions";
drop policy if exists "Admins can read all ratings" on public."puzzle_ratings";
drop policy if exists "Admins can read all results" on public."game_results";
drop policy if exists "Admins can read beta feedback" on public."beta_feedback";
drop policy if exists "Admins can read beta playtests" on public."beta_playtests";
drop policy if exists "Admins can read custom puzzles" on public."custom_puzzles";
drop policy if exists "Admins can read feedback" on public."feedback";
drop policy if exists "Anyone can read published or beta puzzle groups" on public."puzzle_groups";
drop policy if exists "Anyone can read published or beta puzzles" on public."puzzles";
drop policy if exists "Anyone can read published puzzle versions" on public."puzzle_versions";
drop policy if exists "Anyone can read puzzle aggregates" on public."puzzle_aggregates";
drop policy if exists "Users can change own rating" on public."puzzle_ratings";
drop policy if exists "Users can check own archive access" on public."archive_access";
drop policy if exists "Users can rate as themselves" on public."puzzle_ratings";
drop policy if exists "Users can read own game sessions" on public."game_sessions";
drop policy if exists "Users can read own guess events" on public."guess_events";
drop policy if exists "Users can read own hint events" on public."hint_events";
drop policy if exists "Users can read own rating" on public."puzzle_ratings";
drop policy if exists "Users can read own results" on public."game_results";
drop policy if exists "Users can view own roles" on public."user_roles";
drop trigger if exists "game_sessions_sync_status_trigger" on public."game_sessions";
drop trigger if exists "puzzle_versions_immutable" on public."puzzle_versions";
drop trigger if exists "puzzles_current_version_check" on public."puzzles";
drop trigger if exists "update_puzzles_updated_at" on public."puzzles";

-- 3. Foreign keys between Rainbow tables, so the tables below can be dropped in any order without cascade.
alter table if exists public."account_onboarding" drop constraint if exists "account_onboarding_user_id_fkey";
alter table if exists public."accounts" drop constraint if exists "accounts_user_id_fkey";
alter table if exists public."archive_access" drop constraint if exists "archive_access_granted_by_fkey";
alter table if exists public."archive_access" drop constraint if exists "archive_access_user_id_fkey";
alter table if exists public."beta_feedback" drop constraint if exists "beta_feedback_playtest_id_fkey";
alter table if exists public."beta_feedback" drop constraint if exists "beta_feedback_puzzle_id_fkey";
alter table if exists public."beta_feedback" drop constraint if exists "beta_feedback_puzzle_version_id_fkey";
alter table if exists public."beta_playtests" drop constraint if exists "beta_playtests_device_id_fkey";
alter table if exists public."beta_playtests" drop constraint if exists "beta_playtests_puzzle_id_fkey";
alter table if exists public."beta_playtests" drop constraint if exists "beta_playtests_puzzle_version_id_fkey";
alter table if exists public."creator_profiles" drop constraint if exists "creator_profiles_user_id_fkey";
alter table if exists public."custom_puzzle_favorites" drop constraint if exists "custom_puzzle_favorites_custom_puzzle_id_fkey";
alter table if exists public."custom_puzzle_favorites" drop constraint if exists "custom_puzzle_favorites_user_id_fkey";
alter table if exists public."custom_puzzle_results" drop constraint if exists "custom_puzzle_results_custom_puzzle_id_fkey";
alter table if exists public."custom_puzzle_results" drop constraint if exists "custom_puzzle_results_device_id_fkey";
alter table if exists public."custom_puzzle_stats" drop constraint if exists "custom_puzzle_stats_custom_puzzle_id_fkey";
alter table if exists public."custom_puzzles" drop constraint if exists "custom_puzzles_created_by_fkey";
alter table if exists public."device_identities" drop constraint if exists "device_identities_claimed_by_fkey";
alter table if exists public."feedback" drop constraint if exists "feedback_user_id_fkey";
alter table if exists public."game_results" drop constraint if exists "game_results_puzzle_id_fkey";
alter table if exists public."game_results" drop constraint if exists "game_results_user_id_fkey";
alter table if exists public."game_sessions" drop constraint if exists "game_sessions_device_id_fkey";
alter table if exists public."game_sessions" drop constraint if exists "game_sessions_user_id_fkey";
alter table if exists public."hint_events" drop constraint if exists "hint_events_game_session_id_fkey";
alter table if exists public."puzzle_groups" drop constraint if exists "puzzle_groups_puzzle_id_fkey";
alter table if exists public."puzzle_ratings" drop constraint if exists "puzzle_ratings_user_id_fkey";
alter table if exists public."puzzle_versions" drop constraint if exists "puzzle_versions_created_by_fkey";
alter table if exists public."puzzle_versions" drop constraint if exists "puzzle_versions_puzzle_id_fkey";
alter table if exists public."puzzles" drop constraint if exists "puzzles_created_by_fkey";
alter table if exists public."user_roles" drop constraint if exists "user_roles_user_id_fkey";
alter table if exists public."user_streaks" drop constraint if exists "user_streaks_device_id_fkey";
alter table if exists public."user_streaks" drop constraint if exists "user_streaks_user_id_fkey";

-- 4. Functions, by exact signature (before tables: some take a Rainbow table's row type).
drop function if exists public."admin_find_account"(_email text);
drop function if exists public."admin_save_puzzle"(_puzzle_id uuid, _metadata jsonb, _content jsonb);
drop function if exists public."admin_set_custom_puzzle_status"(_puzzle_id uuid, _status text);
drop function if exists public."complete_beta_playtest"(_playtest_id uuid, _device_id text, _device_token text, _won boolean, _mistakes integer, _hints_used boolean);
drop function if exists public."count_own_anonymous_sessions"(_device_id text, _device_token text);
drop function if exists public."create_custom_puzzle"(_creator_name text, _title text, _visibility text, _content jsonb);
drop function if exists public."create_device_identity"();
drop function if exists public."create_game_session"(_puzzle_id text, _device_id text, _device_token text, _entry_context text, _active_time_seconds integer, _mistakes integer, _puzzle_version_id uuid);
drop function if exists public."custom_creator_new_slug"(_name text);
drop function if exists public."custom_ensure_creator_profile"(_uid uuid, _name text);
drop function if exists public."custom_puzzle_new_short_code"();
drop function if exists public."custom_puzzle_public_json"(_p custom_puzzles);
drop function if exists public."custom_random_string"(_alphabet text, _len integer);
drop function if exists public."decline_guest_history"(_device_id text, _device_token text);
drop function if exists public."delete_local_account"(_user_id uuid);
drop function if exists public."delete_my_account"();
drop function if exists public."device_has_importable_history"(_device_id text);
drop function if exists public."ensure_account"();
drop function if exists public."finalize_game_session"(_session_id uuid, _device_id text, _device_token text, _won boolean, _mistakes integer, _active_time_seconds integer, _found_rainbow boolean, _rainbow_solve_index smallint, _solve_order jsonb, _hints_used boolean, _share_grid text, _skip_streak boolean, _local_date text);
drop function if exists public."game_sessions_sync_status"();
drop function if exists public."get_archive_puzzles"();
drop function if exists public."get_creator_profile"(_slug text, _sort text);
drop function if exists public."get_custom_puzzle_by_short_code"(_short_code text);
drop function if exists public."get_custom_puzzle_stats"(_share_id text);
drop function if exists public."get_custom_puzzle"(_share_id text);
drop function if exists public."get_luck_report"(_puzzle_id uuid, _device_id text, _device_token text);
drop function if exists public."get_my_favorites"();
drop function if exists public."get_own_completed_sessions"(_device_id text, _device_token text, _format text);
drop function if exists public."get_own_streak"(_device_id text, _device_token text, _format text);
drop function if exists public."get_puzzle_report"(_puzzle_id uuid);
drop function if exists public."get_puzzle_stats"(_puzzle_id uuid);
drop function if exists public."get_streak_admin_summary"();
drop function if exists public."has_archive_access"(_user_id uuid);
drop function if exists public."has_official_result"(_puzzle_id text, _device_id text, _device_token text);
drop function if exists public."has_role"(_user_id uuid, _role app_role);
drop function if exists public."import_guest_history"(_device_id text, _device_token text);
drop function if exists public."increment_puzzle_aggregate"(_puzzle_id text, _won boolean, _mistakes integer, _time_seconds integer, _first_solve text);
drop function if exists public."luck_eligible_paths"(_puzzle_id text);
drop function if exists public."my_account"();
drop function if exists public."ping"();
drop function if exists public."puzzle_versions_block_update"();
drop function if exists public."puzzles_check_current_version"();
drop function if exists public."rainbow_uid"();
drop function if exists public."record_bonus_rainbow"(_session_id uuid, _device_id text, _device_token text, _guess_number integer, _words jsonb, _correct boolean, _guessed_at timestamp with time zone, _active_time_seconds integer, _groups_solved smallint);
drop function if exists public."record_guess_events"(_session_id uuid, _device_id text, _device_token text, _events jsonb);
drop function if exists public."record_hint_event"(_session_id uuid, _device_id text, _device_token text, _hint_type text, _revealed_at timestamp with time zone, _active_time_seconds integer, _guess_count smallint, _mistakes smallint, _groups_solved smallint, _rainbow_found boolean);
drop function if exists public."record_streak"(_user_id uuid, _device_id text, _won boolean, _local_date text, _format text);
drop function if exists public."reset_beta_playtest"(_puzzle_id uuid, _device_id text, _device_token text);
drop function if exists public."resolve_device_import"(_device_id text, _device_token text);
drop function if exists public."resolve_onboarding"(_device_id text, _device_token text);
drop function if exists public."session_capability_ok"(_session_id uuid, _device_id text, _device_token text);
drop function if exists public."set_custom_puzzle_favorite"(_share_id text, _favorite boolean);
drop function if exists public."skill_score"(_won boolean, _mistakes integer, _solve_order jsonb, _found_rainbow boolean, _rainbow_source text, _format text);
drop function if exists public."start_beta_playtest"(_puzzle_id uuid, _puzzle_version_id uuid, _device_id text, _device_token text);
drop function if exists public."submit_beta_feedback"(_puzzle_id uuid, _puzzle_version_id uuid, _playtest_id uuid, _tester_name text, _fun_rating smallint, _difficulty_rating smallint, _rainbow_fairness_rating smallint, _confusing_or_incorrect text, _additional_comments text, _would_play_again boolean);
drop function if exists public."submit_custom_puzzle_result"(_share_id text, _device_id text, _device_token text, _won boolean, _total_guesses smallint, _run_id uuid);
drop function if exists public."submit_custom_puzzle_result"(_share_id text, _device_id text, _device_token text, _won boolean, _total_guesses smallint);
drop function if exists public."touch_game_session"(_session_id uuid, _device_id text, _device_token text, _active_time_seconds integer, _mistakes integer);
drop function if exists public."update_updated_at_column"();
drop function if exists public."validate_custom_puzzle_content"(_content jsonb);
drop function if exists public."validate_puzzle_content"(_content jsonb);
drop function if exists public."verify_device"(_device_id text, _device_token text);

-- 5. Tables (indexes and remaining constraints go with them). NO cascade: an outside dependency aborts the transaction.
drop table if exists public."account_onboarding";
drop table if exists public."accounts";
drop table if exists public."archive_access";
drop table if exists public."beta_feedback";
drop table if exists public."creator_profiles";
drop table if exists public."custom_puzzle_favorites";
drop table if exists public."custom_puzzle_results";
drop table if exists public."custom_puzzle_stats";
drop table if exists public."feedback";
drop table if exists public."game_results";
drop table if exists public."guess_events";
drop table if exists public."hint_events";
drop table if exists public."luck_score_ceilings";
drop table if exists public."puzzle_aggregates";
drop table if exists public."puzzle_groups";
drop table if exists public."puzzle_ratings";
drop table if exists public."user_roles";
drop table if exists public."user_streaks";
drop table if exists public."beta_playtests";
drop table if exists public."custom_puzzles";
drop table if exists public."game_sessions";
drop table if exists public."device_identities";
drop table if exists public."puzzle_versions";
drop table if exists public."puzzles";

-- 6. Types.
drop type if exists public."app_role";

-- 7. Beta users. Everything not on the owner's keep-list. GoTrue's cascades remove identities, sessions and refresh tokens.
delete from auth.users where id <> all(array['00000000-0000-0000-0000-000000000000']::uuid[]);

-- 8. The migration ledger: the beta-era chain is superseded by the baseline (0001/0002 are recorded when the baseline is applied).
delete from supabase_migrations.schema_migrations where version in ('20260322052030', '20260322053806', '20260322054635', '20260323045030', '20260323051752', '20260704120000', '20260731120000', '20260915231813', '20260916120000', '20260916150000', '20260916220000', '20260916230000', '20260917000000', '20260917010000', '20260917120000', '20260918003000', '20260918010000', '20260918020000', '20260918030000', '20260918040000', '20260919000000', '20260919020000', '20260920000000', '20260921000000', '20260922000000', '20260923000000', '20260924000000', '20260925000000', '20260926000000', '20260927000000', '20260928000000', '20260929000000');

-- 9. What is left of Rainbow in public after this? Nothing, if the lists were complete.
do $$
declare _left text;
begin
  select string_agg(tablename, ', ' order by tablename) into _left from pg_tables where schemaname = 'public'
     and tablename = any(array['account_onboarding', 'accounts', 'archive_access', 'beta_feedback', 'creator_profiles', 'custom_puzzle_favorites', 'custom_puzzle_results', 'custom_puzzle_stats', 'feedback', 'game_results', 'guess_events', 'hint_events', 'luck_score_ceilings', 'puzzle_aggregates', 'puzzle_groups', 'puzzle_ratings', 'user_roles', 'user_streaks', 'beta_playtests', 'custom_puzzles', 'game_sessions', 'device_identities', 'puzzle_versions', 'puzzles']);
  if _left is not null then raise exception 'Aborting: Rainbow tables still present: %', _left; end if;
  select string_agg(tablename, ', ' order by tablename) into _left from pg_tables where schemaname = 'public';
  raise notice 'tables remaining in public (must all be other tenants''): %', coalesce(_left, '(none)');
end $$;

rollback;  -- REHEARSAL: nothing above was kept.
