-- ===========================================================================
-- Custom puzzle statistics: counted replays with lean, fixed-size storage.
--
-- THE EXISTING LIMITATION
--   custom_puzzle_results is UNIQUE (custom_puzzle_id, device_id): one row per
--   device per puzzle, first result kept, every later call a no-op. That was
--   the entire "replay does not inflate stats" guarantee, and it makes a
--   COUNTED replay impossible: a second completed run from the same device
--   has nowhere to go. Storing one permanent row per replay would fix that but
--   grows without bound.
--
-- THE MODEL
--   1. custom_puzzle_stats -- ONE fixed-size aggregate row per puzzle: wins,
--      losses, five guess buckets (4,5,6,7,8+) and the sum of guesses over
--      wins. Every read is O(1); nothing per-play is stored here.
--   2. custom_puzzle_results stays one row per (puzzle, device) -- the same
--      cardinality as today -- and now also holds recent_run_ids: the last
--      10 run ids that device has had counted. That bounded window is the
--      idempotency guard: a refresh, remount or retry of a run that was
--      already counted finds its id there and changes nothing. The row's
--      original won / total_guesses columns keep meaning "this device's first
--      result" and are no longer read by anything.
--   3. submit_custom_puzzle_result gains _run_id (one id per playthrough,
--      generated by the client and kept in that run's local progress). A
--      completed replay has a new run id, so it counts once more; clicking
--      Replay alone, or abandoning a replay, never reaches this function.
--
-- Wins/guess buckets: losses are a separate counter and never enter the
-- average or the distribution.
--
-- Backward compatible: the original 5-argument submit_custom_puzzle_result is
-- kept as a wrapper with a run id derived from (puzzle, device), so a client
-- bundle cached from before this deploy behaves exactly as it used to
-- (first result per device only).
--
-- Forward-only. Backfill is deterministic: each existing results row was one
-- completed play, so it becomes exactly one count.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. aggregate counters
-- ---------------------------------------------------------------------------
create table public.custom_puzzle_stats (
  custom_puzzle_id uuid primary key references public.custom_puzzles(id) on delete cascade,
  wins             integer not null default 0 check (wins >= 0),
  losses           integer not null default 0 check (losses >= 0),
  guesses_4        integer not null default 0 check (guesses_4 >= 0),
  guesses_5        integer not null default 0 check (guesses_5 >= 0),
  guesses_6        integer not null default 0 check (guesses_6 >= 0),
  guesses_7        integer not null default 0 check (guesses_7 >= 0),
  guesses_8_plus   integer not null default 0 check (guesses_8_plus >= 0),
  -- Sum of total_guesses over WINS only; avg = win_guess_total / wins.
  win_guess_total  bigint  not null default 0 check (win_guess_total >= 0),
  updated_at       timestamptz not null default now()
);

comment on table public.custom_puzzle_stats is
  'One fixed-size aggregate row per custom puzzle (wins, losses, five guess buckets). Written only by submit_custom_puzzle_result; read only by get_custom_puzzle_stats and get_creator_profile.';

alter table public.custom_puzzle_stats enable row level security;
revoke all on table public.custom_puzzle_stats from anon, authenticated;
-- No policies: RPC-only, same as custom_puzzle_results.

-- ---------------------------------------------------------------------------
-- 2. per-device idempotency window
-- ---------------------------------------------------------------------------
alter table public.custom_puzzle_results
  add column recent_run_ids uuid[] not null default '{}';

comment on column public.custom_puzzle_results.recent_run_ids is
  'The last 10 run ids this device has had counted for this puzzle (newest first). Bounded idempotency window; see submit_custom_puzzle_result.';

-- ---------------------------------------------------------------------------
-- 3. deterministic backfill: every existing row is one completed play
-- ---------------------------------------------------------------------------
insert into public.custom_puzzle_stats
  (custom_puzzle_id, wins, losses, guesses_4, guesses_5, guesses_6, guesses_7, guesses_8_plus, win_guess_total)
select r.custom_puzzle_id,
       count(*) filter (where r.won),
       count(*) filter (where not r.won),
       count(*) filter (where r.won and r.total_guesses <= 4),
       count(*) filter (where r.won and r.total_guesses = 5),
       count(*) filter (where r.won and r.total_guesses = 6),
       count(*) filter (where r.won and r.total_guesses = 7),
       count(*) filter (where r.won and r.total_guesses >= 8),
       coalesce(sum(r.total_guesses) filter (where r.won), 0)
  from public.custom_puzzle_results r
 group by r.custom_puzzle_id;

-- ---------------------------------------------------------------------------
-- 4. submit_custom_puzzle_result -- now run-aware
-- ---------------------------------------------------------------------------
create or replace function public.submit_custom_puzzle_result(
  _share_id text,
  _device_id text,
  _device_token text,
  _won boolean,
  _total_guesses smallint,
  _run_id uuid
)
returns boolean
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  _cpid    uuid;
  _rows    integer;
begin
  if not public.verify_device(_device_id, _device_token) then
    return false;
  end if;

  if _won is null then
    raise exception 'won is required' using errcode = 'invalid_parameter_value';
  end if;
  if _total_guesses is null or _total_guesses < 0 or _total_guesses > 60 then
    raise exception 'total_guesses out of range' using errcode = 'invalid_parameter_value';
  end if;
  if _run_id is null then
    raise exception 'run_id is required' using errcode = 'invalid_parameter_value';
  end if;

  select id into _cpid
    from public.custom_puzzles
   where share_id = _share_id
     and moderation_status = 'active';

  if _cpid is null then
    return false;
  end if;

  -- First result from this device: the row is created holding this run id.
  insert into public.custom_puzzle_results (custom_puzzle_id, device_id, won, total_guesses, recent_run_ids)
  values (_cpid, _device_id, _won, _total_guesses, array[_run_id])
  on conflict (custom_puzzle_id, device_id) do nothing;
  get diagnostics _rows = row_count;

  if _rows = 0 then
    -- Existing device row: count this run only if its id is not already in the
    -- window. The UPDATE re-checks the predicate under the row lock, so two
    -- simultaneous submissions of one run count once.
    update public.custom_puzzle_results
       set recent_run_ids = (array[_run_id] || recent_run_ids)[1:10]
     where custom_puzzle_id = _cpid
       and device_id = _device_id
       and not (_run_id = any (recent_run_ids));
    get diagnostics _rows = row_count;
  end if;

  if _rows > 0 then
    insert into public.custom_puzzle_stats as s
      (custom_puzzle_id, wins, losses, guesses_4, guesses_5, guesses_6, guesses_7, guesses_8_plus, win_guess_total)
    values (
      _cpid,
      case when _won then 1 else 0 end,
      case when _won then 0 else 1 end,
      case when _won and _total_guesses <= 4 then 1 else 0 end,
      case when _won and _total_guesses = 5 then 1 else 0 end,
      case when _won and _total_guesses = 6 then 1 else 0 end,
      case when _won and _total_guesses = 7 then 1 else 0 end,
      case when _won and _total_guesses >= 8 then 1 else 0 end,
      case when _won then _total_guesses else 0 end
    )
    on conflict (custom_puzzle_id) do update
      set wins            = s.wins + excluded.wins,
          losses          = s.losses + excluded.losses,
          guesses_4       = s.guesses_4 + excluded.guesses_4,
          guesses_5       = s.guesses_5 + excluded.guesses_5,
          guesses_6       = s.guesses_6 + excluded.guesses_6,
          guesses_7       = s.guesses_7 + excluded.guesses_7,
          guesses_8_plus  = s.guesses_8_plus + excluded.guesses_8_plus,
          win_guess_total = s.win_guess_total + excluded.win_guess_total,
          updated_at      = now();
  end if;

  return true;
end;
$$;

revoke all on function public.submit_custom_puzzle_result(text, text, text, boolean, smallint, uuid) from public;
grant execute on function public.submit_custom_puzzle_result(text, text, text, boolean, smallint, uuid) to anon, authenticated, service_role;

comment on function public.submit_custom_puzzle_result(text, text, text, boolean, smallint, uuid) is
  'Counts one completed run (identified by _run_id) for (custom_puzzle, device). A repeat of the same run is a no-op that still returns true; a completed replay has a new run id and counts once more. Never writes to any official or Beta table.';

-- Legacy 5-argument form: same behaviour as before this migration (first
-- result per device). The run id is derived from (puzzle, device), so every
-- repeat call is a no-op.
create or replace function public.submit_custom_puzzle_result(
  _share_id text,
  _device_id text,
  _device_token text,
  _won boolean,
  _total_guesses smallint
)
returns boolean
language sql
volatile
security definer
set search_path = public
as $$
  select public.submit_custom_puzzle_result(
    _share_id, _device_id, _device_token, _won, _total_guesses,
    md5(coalesce(_share_id, '') || ':' || coalesce(_device_id, ''))::uuid
  );
$$;

revoke all on function public.submit_custom_puzzle_result(text, text, text, boolean, smallint) from public;
grant execute on function public.submit_custom_puzzle_result(text, text, text, boolean, smallint) to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 5. get_custom_puzzle_stats -- aggregates only, from the counter row
--
-- Always returns all five buckets. completed_plays = wins + losses. The
-- average is over wins only. finished_plays is kept as an alias for clients
-- cached from before this migration.
-- ---------------------------------------------------------------------------
create or replace function public.get_custom_puzzle_stats(_share_id text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  _cpid uuid;
  s     public.custom_puzzle_stats%rowtype;
begin
  select id into _cpid
    from public.custom_puzzles
   where share_id = _share_id
     and moderation_status = 'active';

  if _cpid is null then
    return null;
  end if;

  select * into s from public.custom_puzzle_stats where custom_puzzle_id = _cpid;

  return jsonb_build_object(
    'completed_plays', coalesce(s.wins, 0) + coalesce(s.losses, 0),
    'finished_plays',  coalesce(s.wins, 0) + coalesce(s.losses, 0),
    'wins',            coalesce(s.wins, 0),
    'losses',          coalesce(s.losses, 0),
    'avg_guesses',     case when coalesce(s.wins, 0) > 0
                            then round(s.win_guess_total::numeric / s.wins, 2)
                            else 0 end,
    'guess_distribution', jsonb_build_object(
      '4',  coalesce(s.guesses_4, 0),
      '5',  coalesce(s.guesses_5, 0),
      '6',  coalesce(s.guesses_6, 0),
      '7',  coalesce(s.guesses_7, 0),
      '8+', coalesce(s.guesses_8_plus, 0)
    )
  );
end;
$$;

comment on function public.get_custom_puzzle_stats(text) is
  'Aggregate completed-play stats for one custom puzzle (by share_id, so Private stats require possessing the link): completed plays, wins, losses, average guesses over wins, and the fixed 4/5/6/7/8+ distribution. Never returns anything row-level.';

-- ---------------------------------------------------------------------------
-- 6. get_creator_profile -- "plays" now means completed plays (wins + losses),
--    not the number of distinct devices. Otherwise identical to the version
--    in 20260920000000.
-- ---------------------------------------------------------------------------
create or replace function public.get_creator_profile(_slug text, _sort text default 'newest')
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  _uid   uuid;
  _name  text;
  _s     text := case when _sort in ('newest', 'plays', 'favorites') then _sort else 'newest' end;
begin
  select user_id, display_name into _uid, _name
    from public.creator_profiles
   where public_slug = _slug;
  if _uid is null then
    return null;
  end if;

  return (
    with pub as (
      select cp.title,
             cp.content ->> 'mode' as mode,
             cp.short_code,
             (select coalesce(s.wins + s.losses, 0) from public.custom_puzzle_stats s where s.custom_puzzle_id = cp.id) as plays,
             (select count(*) from public.custom_puzzle_favorites f where f.custom_puzzle_id = cp.id) as favs,
             cp.created_at
        from public.custom_puzzles cp
       where cp.created_by = _uid
         and cp.visibility = 'public'
         and cp.moderation_status = 'active'
    )
    select jsonb_build_object(
      'display_name',    _name,
      'public_slug',     _slug,
      'puzzle_count',    (select count(*) from pub),
      'total_plays',     (select coalesce(sum(plays), 0) from pub),
      'total_favorites', (select coalesce(sum(favs), 0) from pub),
      'puzzles',         coalesce((
        select jsonb_agg(
                 jsonb_build_object(
                   'title',          q.title,
                   'mode',           q.mode,
                   'short_code',     q.short_code,
                   'finished_plays', q.plays,
                   'favorite_count', q.favs,
                   'created_at',     q.created_at
                 )
                 order by (case _s when 'plays' then q.plays end) desc nulls last,
                          (case _s when 'favorites' then q.favs end) desc nulls last,
                          q.created_at desc)
          from (select * from pub
                 order by (case _s when 'plays' then plays end) desc nulls last,
                          (case _s when 'favorites' then favs end) desc nulls last,
                          created_at desc
                 limit 100) q
      ), '[]'::jsonb)
    )
  );
end;
$$;

revoke all on function public.get_creator_profile(text, text) from public;
grant execute on function public.get_creator_profile(text, text) to anon, authenticated, service_role;

comment on function public.get_creator_profile(text, text) is
  'Public creator page data: display name, totals and the creator''s Public, non-moderated puzzles only (sort: newest | plays | favorites). Returns only explicitly listed safe fields.';
