/**
 * Talking to the disposable local Supabase stack: is it up, what are its
 * keys, and how does `.env.e2e` get written.
 *
 * The keys are never hardcoded. They are read back out of the running
 * stack's own `supabase status`, which means:
 *   * nothing secret is committed, because the local stack's keys are demo
 *     JWTs it generates itself;
 *   * nothing goes stale when the CLI changes them;
 *   * and there is no constant anywhere in this repository that a future
 *     copy-paste could turn into a production key.
 */

import { writeFileSync } from "node:fs";
import { E2E_ENV_FILE, E2E_PORTS, E2E_PROJECT_DIR } from "../../env.ts";
import { supabaseCapture } from "./process.ts";

export interface StackKeys {
  apiUrl: string;
  dbUrl: string;
  anonKey: string;
  serviceRoleKey: string;
}

/**
 * Parses `supabase status -o env`, which prints plain `KEY="value"` lines —
 * the most stable of the CLI's output formats across versions.
 */
export function readStackStatus(): { ok: true; keys: StackKeys } | { ok: false; error: string } {
  const result = supabaseCapture(E2E_PROJECT_DIR, ["status", "-o", "env"]);
  if (result.code !== 0) {
    return { ok: false, error: (result.stderr || result.stdout || "supabase status failed").trim() };
  }

  const values: Record<string, string> = {};
  for (const line of result.stdout.split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*"?([^"]*)"?\s*$/);
    if (match) values[match[1]] = match[2];
  }

  const anonKey = values.ANON_KEY ?? values.PUBLISHABLE_KEY ?? "";
  const serviceRoleKey = values.SERVICE_ROLE_KEY ?? values.SECRET_KEY ?? "";
  const apiUrl = values.API_URL ?? `http://127.0.0.1:${E2E_PORTS.api}`;
  const dbUrl = values.DB_URL ?? `postgresql://postgres:postgres@127.0.0.1:${E2E_PORTS.db}/postgres`;

  if (!anonKey || !serviceRoleKey) {
    return {
      ok: false,
      error:
        "`supabase status` did not report an anon and service-role key. " +
        `Saw: ${Object.keys(values).join(", ") || "(nothing)"}`,
    };
  }

  // The CLI reports the gateway on localhost; pin it to the loopback literal
  // so the safety guard, the browser and the seeder all agree on one origin
  // (and so a machine where "localhost" resolves to ::1 first behaves the
  // same as one where it does not).
  return {
    ok: true,
    keys: {
      apiUrl: apiUrl.replace("//localhost:", "//127.0.0.1:"),
      dbUrl: dbUrl.replace("@localhost:", "@127.0.0.1:"),
      anonKey,
      serviceRoleKey,
    },
  };
}

/**
 * Writes `.env.e2e` at the repository root, where Vite picks it up for
 * `--mode e2e`. Git-ignored; regenerated by every `npm run e2e:up`.
 */
export function writeE2eEnvFile(keys: StackKeys): string {
  const body = [
    "# GENERATED by `npm run e2e:up` — do not edit, do not commit.",
    "# These are the disposable local Supabase stack's own demo keys, read",
    "# back out of `supabase status`. They are worthless outside this",
    "# machine's containers. See .env.e2e.example and e2e/README.md.",
    "",
    `VITE_SUPABASE_URL=${keys.apiUrl}`,
    `VITE_SUPABASE_PUBLISHABLE_KEY=${keys.anonKey}`,
    "",
    "# Server-side only: used by the seeder and by test helpers that need to",
    "# set up or inspect state. Never reaches the browser bundle (no VITE_",
    "# prefix), and only ever used against the URL above.",
    `E2E_SERVICE_ROLE_KEY=${keys.serviceRoleKey}`,
    `E2E_DB_URL=${keys.dbUrl}`,
    `E2E_APP_URL=http://127.0.0.1:${E2E_PORTS.app}`,
    "",
    "# The support CTA must stay hidden in tests (custom.spec.ts asserts it).",
    "VITE_SUPPORT_URL=",
    "",
  ].join("\n");
  writeFileSync(E2E_ENV_FILE, body, "utf8");
  return E2E_ENV_FILE;
}
